### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by wkdcode-mat** [rorecek/laravel-ulid#8]
When you have a moment please could you update composer.json to allow support for PHP 8? 

I can confirm the package is working perfectly on PHP 8. At the moment to start a PHP 8, Laravel 8 built using your package you need run composer with _--ignore-platform-reqs_ flag
 
Hopefully you just need to update your require PHP _^7.0|^8.0_ in your composer.json to enable support.

Many thanks

Mat

**Comment by rorecek** [comment]
Fixed :)
